import local_time
import weather
import config

words = ["Qual é o meu nome?",
        "Qual o nome do meu cachorro?",
        "Que dia é hoje",
        "Obrigado",
        "Qual é o seu nome",
        "Você está bem",
        "Como você está",
        "Que horas são",
        "Que hora é agora",
        "Qual a marca da ração do cachorro",
        "Qual a minha comida preferida?",
        "como está o clima hoje",
        "quantos graus está hoje",
        "como está o tempo",
        "Qual o nome do meu gato?",
]

answers = [
        f"Você se chama {config.my_name}",
        f"O nome do cachorro é {config.my_dog_name}",
        local_time.current_date_formatted(),
        "De nada",
        f"Meu nome é {config.assistant_name}, prazer.",
        "Estou ótimo, obrigado por perguntar",
        "Estou muito bem e você?",
        "Agora são " + local_time.current_hour(),
        "Agora são " + local_time.current_hour(),
        f"A ração do {config.my_dog_name} é a {config.dog_food_name}",
        f"A sua comida preferida é {config.my_favourite_food}",
        weather.weather(),
        weather.weather(),
        weather.weather(),
        f"O nome do gato é {config.my_cat_name}",
]

numbers_in_words = [
    "um",
    "dois",
    "tres",
    "quatro",
    "cinco",
    "seis",
    "sete",
    "oito",
    "nove",
    "dez",
    "onze",
    "doze",
    "treze",
    "quatorze",
    "quinze",
    "dezesseis",
    "dezessete",
    "dezoito",
    "dezenove",
    "vinte",
    "vinte e um",
    "vinte e dois",
    "vinte e tres",
    "vinte e quatro",
    "vinte e cinco",
    "vinte e seis",
    "vinte e sete",
    "vinte e oito",
    "vinte e nove",
    "trinta",
    "trinta e um",
]